#!/usr/bin/env ruby
require 'json'
require './lib/golden-gardens/ServiceTester'

unless ARGV.length == 2
  $stderr.puts("Usage: #{$0} contract-path endpoint-root-url")
  exit(1)
end

contract = JSON.parse(File.read(ARGV[0]))
endpointRoot = ARGV[1]

tester = ServiceTester.new(endpointRoot)
result = tester.validate(contract)

if result.ok?
  puts 'ok'
else
  $stderr.puts("Validation failed:")

  result.errors.each do |error|
    $stderr.puts(error)
  end

  exit(1)
end
